name: Lint

on:
  push:
    branches: [main, dev]  # Temporairement ajouté dev pour tester
  pull_request:
    branches: [main, dev]

jobs:
  build-check:
    name: Build ${{ matrix.service }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true  # Stop all jobs if one fails
      matrix:
        service:
          - Gateway-Service
          - User-Service
          - Announcement-Service
          - Application-Service
          - Chat-Service
          - Favorite-Service
          - Log-Service
          - Payment-Service
          - Rating-Service
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Make mvnw executable
        run: |
          cd ${{ matrix.service }}
          chmod +x mvnw
      
      - name: Verify Maven compilation
        run: |
          cd ${{ matrix.service }}
          echo "🔨 Compiling ${{ matrix.service }}..."
          ./mvnw clean compile -q
      

