name: Update Main Repo

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches: [main]

jobs:
  update-main-repo:
    name: Update Main Repo from Back
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set up Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone main repo
        run: |
          git clone https://x-access-token:${{ secrets.MAIN_REPO_TOKEN }}@github.com/${{ secrets.MAIN_REPO_OWNER }}/IWAProject.git
          cd IWAProject
          git checkout main
          
          git config -f .gitmodules submodule.back.url https://x-access-token:${{ secrets.MAIN_REPO_TOKEN }}@github.com/${{ github.repository }}.git
          git config -f .gitmodules submodule.front.url https://x-access-token:${{ secrets.MAIN_REPO_TOKEN }}@github.com/${{ secrets.MAIN_REPO_OWNER }}/IWAProject-Front.git
          
          git submodule sync
          git submodule update --init --recursive

      - name: Update back submodule to latest main
        run: |
          cd IWAProject/back
          git fetch origin main
          git checkout origin/main
          cd ..

          git add back
          git diff-index --quiet HEAD || git commit -m "chore: update back submodule to latest main [skip ci]"

      - name: Push changes to main repo
        run: |
          cd IWAProject
          git push origin main || echo "No changes to push"

      - name: Notify update success
        if: success()
        run: echo "✅ Successfully updated main repo with back changes!"
